version: '2'

services:
  consul:
    container_name: consul
    image: progrium/consul:latest
    command: -server -bootstrap -ui-dir /ui
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
      - "0.0.0.0:53:53/udp"
    networks:
      - bridge

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    command: --storageEngine wiredTiger
    volumes:
      # This would exist on MacOSX Host - permissions errors
      #- /Users/mitch/git/docker-microservice-demo/mongo/data:/data/db
      # Map this to boot2docker host FileSystem to keep mongo data between
      # container restarts
      - ./mongodata:/data/db
    networks:
      - bridge

  #
  # Service Discovery - Registrator
  #
  registrator:
    container_name: registrator
    command: -ip 127.0.0.1 -ttl 30 -ttl-refresh 15 consul://localhost:8500
    image: gliderlabs/registrator:latest
    network_mode: "host"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"

  giles:
    container_name: giles
    image: giles:latest
    ports:
      - "5000:5000"
    networks:
      - bridge


networks:
  bridge:
